# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Date_Of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Address', max_length=64, null=True),
        ),
    ]
