# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20161203_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone_num',
            new_name='Phone_number',
        ),
    ]
