# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_date', models.DateField()),
                ('auction_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_bid', models.BigIntegerField(help_text='user bidding', null=True)),
                ('Time_of_Bid', models.TimeField(auto_now=True, null=True)),
                ('Bidder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Car_Name', max_length=18)),
                ('manufacture_year', models.CharField(help_text='E.g.: 2015/2016', max_length=120)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='live_auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_of_Bid', models.TimeField(auto_now=True, null=True)),
                ('initial_bid', models.BigIntegerField(help_text='the initial bid', null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.auction')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='l_auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.live_auction'),
        ),
        migrations.AddField(
            model_name='auction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.item'),
        ),
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
