# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.CharField(choices=[('C', 'Cars'), ('P', 'Parts')], max_length=64, null=True, verbose_name='Product_type'),
        ),
    ]
