# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_auto_20161129_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live_auction',
            name='Time_of_Bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('P', 'Premium'), ('F', 'Freemium')], max_length=64, null=True, verbose_name='auction_type'),
        ),
        migrations.AddField(
            model_name='live_auction',
            name='Time_of_Auction',
            field=models.TimeField(null=True),
        ),
    ]
