# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auction', '0003_auto_20161129_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.BigIntegerField()),
                ('Payment_Method', models.CharField(choices=[('Cash', 'Cash'), ('Knet', 'Knet'), ('Visa', 'Visa')], max_length=50, verbose_name='Payment method')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
