# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auction', '0008_auto_20170105_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live_auction',
            old_name='Time_of_Auction',
            new_name='End_Time_of_Auction',
        ),
        migrations.AddField(
            model_name='live_auction',
            name='auction_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Auction_Winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='live_auction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
