# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0010_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.AddField(
            model_name='item',
            name='pictures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auction.Picture'),
        ),
    ]
