# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0013_picture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_auction',
            name='winining_bid',
            field=models.BigIntegerField(null=True),
        ),
    ]
