# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0014_live_auction_winining_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pictures',
        ),
        migrations.AddField(
            model_name='item',
            name='pictures',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
