# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0015_auto_20170116_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pictures',
        ),
        migrations.AddField(
            model_name='item',
            name='pictures',
            field=models.ManyToManyField(to='Auction.Picture'),
        ),
    ]
