# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Account support', 'Account support'), ('technical support', 'technical support'), ('transaction support', 'transaction support')], max_length=64, null=True, verbose_name='category')),
                ('question', models.CharField(max_length=200, verbose_name='question')),
                ('answer', models.CharField(max_length=300, verbose_name='answer')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Account support', 'Account support'), ('technical support', 'technical support'), ('transaction support', 'transaction support')], max_length=64, null=True)),
                ('subject', models.CharField(max_length=64, verbose_name='subject')),
                ('body_of_the_ticket', models.TextField(max_length=300, verbose_name='body of the ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
